export enum JobLogAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  ASSIGN_TEAM = 'ASSIGN_TEAM',
  ASSIGN_CLIENT = 'ASSIGN_CLIENT',
  ASSIGN_RECRUITER = 'ASSIGN_RECRUITER',
  STATUS_UPDATE = 'STATUS_UPDATE',
}
