export const _wordRx = /[A-Za-z][A-Za-z.&\-\u00C0-\u024F]*/g;

export const CANDIDATE_SIDE = [
  "i am",
  "i m",
  "i’m",
  "im",
  "my resume",
  "my cv",
  "cv attached",
  "resume attached",
  "i have",
  "i possess",
  "my experience",
  "my skills",
  "i worked",
  "i am available",
  "open to work",
  "opentowork",
  "actively looking",
  "looking for job",
  "need a job",
  "apply now",
  "apply here",
  "how to apply",
  "application form",
  "salary expectation",
  "stipend",
  "internship application",
  "learn",
  "course",
  "tutorial",
  "bootcamp",
  "syllabus",
];

export const PAGE_WORDS = [
  "page",
  "pages",
  "screen",
  "screens",
  "section",
  "sections",
  "view",
  "views",
  "panel",
  "panels",
  "tab",
  "tabs",
  "area",
  "areas",
];
export const PRONOUNS = ["this", "that", "the", "my"];
export const FILLERS_PREFIX = [
  "please",
  "kindly",
  "can you",
  "could you",
  "will you",
  "would you",
  "hey",
  "ok",
  "okay",
  "alright",
];
export const FILLERS_SUFFIX = [
  "please",
  "now",
  "thanks",
  "thank you",
  "right now",
  "for me",
  "for now",
  "if you can",
];

export const VERBS = [
  "go",
  "go to",
  "navigate",
  "navigate to",
  "open",
  "show",
  "launch",
  "access",
  "display",
  "view",
  "visit",
  "enter",
  "load",
  "take me",
  "bring up",
  "head to",
  "jump to",
  "switch to",
  "move to",
  "get me to",
  "route to",
  "lead me to",
  "switch",
  "take me to",
  "bring me to",
  "open up",
  "pull up",
  "pop open",
];

export const HIRING_VERBS = [
  "find",
  "get",
  "search",
  "show",
  "lookup",
  "look up",
  "fetch",
  "source",
  "sourcing",
  "recruit",
  "hire",
  "hiring",
  "shortlist",
  "short-list",
  "screen",
  "screening",
  "need",
  "looking for",
  "seek",
  "seeking",
  "want",
  "require",
  "required",
  "fill",
  "filling",
  "filter",
  "filter by",
  "apply filter",
  "apply filters",
  "list",
  "give me",
  "which",
  "who are",
  "who are the",
  "list all",
  "show all",
  "please show",
  "can you list",
  "can you get",
  "could you list",
  "would you list",
];
export const HIRING_NOUNS = [
  "candidate",
  "candidates",
  "profile",
  "profiles",
  "talent",
  "role",
  "roles",
  "position",
  "positions",
  "opening",
  "openings",
  "vacancy",
  "vacancies",
  "job",
  "jobs",
  "pipeline",
  "bench",
];

export const KITS: Record<string, string[]> = {
  // Eng – FE / BE / FS
  FE_generic: ["React", "TypeScript", "CSS", "Webpack"],
  FE_react: ["React", "TypeScript", "Redux", "Jest"],
  FE_next: ["Next.js", "React", "TypeScript", "Vercel"],
  FE_angular: ["Angular", "TypeScript", "RxJS", "Jasmine"],
  FE_vue: ["Vue", "TypeScript", "Pinia", "Vite"],
  FE_svelte: ["Svelte", "TypeScript", "Vite", "Testing Library"],
  BE_node: ["Node.js", "Express/Nest", "PostgreSQL", "Docker"],
  BE_java: ["Java", "Spring Boot", "PostgreSQL", "Docker"],
  BE_python: ["Python", "Django/FastAPI", "PostgreSQL", "Docker"],
  BE_go: ["Go", "Gin/Fiber", "PostgreSQL", "Docker"],
  BE_rust: ["Rust", "Tokio/Actix", "PostgreSQL", "Docker"],
  BE_scala: ["Scala", "Akka/Play", "Kafka", "Cassandra"],
  BE_php: ["PHP", "Laravel", "MySQL", "Nginx"],
  BE_ruby: ["Ruby", "Rails", "PostgreSQL", "Sidekiq"],
  BE_dotnet: ["C#", ".NET", "SQL Server", "Azure"],
  FS_generic: ["React", "Node.js", "PostgreSQL", "Docker"],

  // Mobile
  ANDROID: ["Kotlin", "Android SDK", "Jetpack", "Gradle"],
  IOS: ["Swift", "UIKit/SwiftUI", "Xcode", "Combine"],
  RN: ["React Native", "TypeScript", "Redux", "Jest"],
  FLUTTER: ["Flutter", "Dart", "Bloc", "Firebase"],

  // Data / ML / AI / BI
  DS: ["Python", "Pandas", "Scikit-learn", "SQL"],
  DE: ["Python", "Spark", "Airflow", "dbt"],
  DA: ["SQL", "Power BI", "DAX", "Excel"],
  AE: ["dbt", "SQL", "Snowflake", "Airflow"],
  MLE: ["Python", "PyTorch", "MLflow", "Docker"],
  NLP: ["Python", "Transformers", "spaCy", "PyTorch"],
  CV: ["Python", "OpenCV", "PyTorch", "NumPy"],
  BI: ["Power BI", "Tableau", "SQL", "DAX"],

  // Cloud / DevOps / SRE / Security
  DEVOPS: ["AWS", "Kubernetes", "Terraform", "Docker"],
  SRE: ["Kubernetes", "Prometheus", "Grafana", "Terraform"],
  PLATFORM: ["Kubernetes", "Helm", "Terraform", "GitHub Actions"],
  CLOUD_AWS: ["AWS", "IAM", "VPC", "CloudFormation"],
  CLOUD_AZ: ["Azure", "AKS", "Azure DevOps", "Bicep"],
  CLOUD_GCP: ["GCP", "GKE", "IAM", "Cloud Build"],
  SEC_ENG: ["Threat Modeling", "AppSec", "OWASP", "Burp Suite"],
  SEC_ANALYST: ["SIEM", "SOC", "Incident Response", "Splunk"],
  APPSEC: ["OWASP", "SAST/DAST", "Threat Modeling", "Burp Suite"],
  PENTEST: ["Burp Suite", "OSCP", "Nmap", "OWASP"],

  // Enterprise apps
  SALESFORCE: ["Apex", "LWC", "SOQL", "Flows"],
  SERVICENOW: ["Glide", "Flow Designer", "Catalog/CMDB", "Scripting"],
  SHAREPOINT: ["SPFx", "TypeScript", "SharePoint Online", "Power Automate"],
  SAP: ["ABAP", "Fiori/UI5", "RFC/BAPI", "IDoc"],

  // Embedded / Firmware / IoT
  EMBEDDED: ["C/C++", "RTOS", "I2C/SPI", "ARM"],
  FIRMWARE: ["C", "UART/I2C/SPI", "FreeRTOS", "Debugging"],
  IOT: ["MQTT", "ESP32", "FreeRTOS", "AWS IoT"],

  // Game / Graphics / Web3
  UNITY: ["Unity", "C#", "URP/HDRP", "Burst/Jobs"],
  UNREAL: ["Unreal Engine", "C++", "Blueprints", "Niagara"],
  WEB3: ["Solidity", "Hardhat", "Ethers.js", "Smart Contracts"],

  // Product / Project / BA / Writing
  PM: ["Roadmapping", "Jira", "A/B Testing", "Stakeholder Mgmt"],
  PMM: ["Positioning", "Messaging", "Market Research", "Launches"],
  SCRUM: ["Scrum", "Sprint Planning", "Backlog Mgmt", "Jira"],
  PROJECT: ["Project Planning", "Risk Mgmt", "MS Project/Jira", "Reporting"],
  PROGRAM: [
    "Portfolio Mgmt",
    "OKRs",
    "Cross-functional Leadership",
    "Roadmaps",
  ],
  BA: ["Requirements", "Process Mapping", "SQL", "User Stories"],
  TECH_WRITER: ["API Docs", "Markdown", "Diagrams", "Information Architecture"],

  // Design / Research / Content
  PDESIGN: ["Figma", "Design Systems", "Prototyping", "Accessibility"],
  UXD: ["Figma", "User Flows", "Prototyping", "Design Systems"],
  UID: ["Figma", "Visual Design", "Prototyping", "Accessibility"],
  UXR: ["User Interviews", "Usability Testing", "Surveys", "Heuristic Eval"],
  GRAPHIC: ["Adobe Illustrator", "Photoshop", "Branding", "Layout"],
  CONTENT: ["SEO Writing", "Editing", "CMS", "Research"],
  SEO: [
    "Keyword Research",
    "On-page SEO",
    "Technical SEO",
    "GA/Search Console",
  ],
  SEM: ["Google Ads", "Bing Ads", "A/B Testing", "Conversion Tracking"],
  SOCIAL: [
    "Content Calendar",
    "Community Mgmt",
    "Analytics",
    "Short-form Video",
  ],

  // Sales / BizDev / CS / Solutions
  SDR: ["Cold Outreach", "Discovery", "Lead Qualification", "CRM"],
  BDR: ["Pipeline Generation", "Outbound", "Email Sequences", "CRM"],
  BD: ["Partnerships", "Lead Gen", "Negotiation", "CRM"],
  SALES_MGR: ["Forecasting", "Team Coaching", "Pipeline Mgmt", "Playbooks"],
  CSM: ["Onboarding", "QBRs", "Renewals", "Churn Mitigation"],
  TAM: ["Customer Architecture", "Escalation Mgmt", "SLA/SLO", "Cloud"],
  SOL_ARCH: ["Solution Design", "Cloud Architecture", "Terraform", "K8s"],
  SOL_ENG: ["Pre-sales Demos", "POCs", "APIs", "Cloud"],
  PRESALES: ["Discovery", "RFPs", "Demo Storytelling", "POCs"],

  // HR / People / Ops / Finance / Legal / Admin
  RECRUITER: ["Sourcing", "ATS", "Interviewing", "Offer Negotiation"],
  HR: ["Employee Relations", "HRIS", "Payroll", "Policies"],
  OPS_MGR: ["Process Improvement", "KPIs", "Budgeting", "Cross-functional"],
  SUPPLY: ["Procurement", "Inventory", "Logistics", "Forecasting"],
  FIN_ANALYST: ["Excel/Sheets", "Financial Modeling", "FP&A", "Dashboards"],
  ACCOUNTANT: ["GL", "AP/AR", "Reconciliation", "Tax"],
  LEGAL: ["Contract Review", "Compliance", "Legal Research", "Drafting"],
  OFFICE_ADMIN: ["Scheduling", "Calendars", "Travel", "Vendor Mgmt"],
  DATA_ENTRY: ["Typing", "Excel", "Data Cleaning", "Accuracy"],

  // Support / QA / DevRel
  QA: ["Selenium/Cypress", "Test Plans", "Postman", "Jest"],
  SDET: ["Java", "Selenium", "TestNG", "REST Assured"],
  DEVREL: ["Talks/Docs", "DX Feedback", "Sample Apps", "Community"],
  SUPPORT: ["Troubleshooting", "Ticketing", "Customer Comms", "SLA"],
};
