export const TEST_SENTENCES = [
  "search for python developer with 7 years of experience in london",
  "Looking for 7 years experienced Python developer in Turkey",
  "get me a frontend engineer with 5 years of experience in Berlin",
  "could you find me a frontend engineer in Berlin with 5 years of experience",
  "please get me a Python developer with 7 years of experience in London",
  "show me a Python developer in Turkey with 7 years experience",
  "kindly search for a senior iOS developer located in Toronto please",
  "get me a QA tester with 18 months experience in Lisbon",
  "i need a security analyst from Dubai with minimum 2 years",
  "find a machine learning specialist over 8 years in New York City",
  "please show the sales manager in Rome right now",
  "bring up a system administrator at Berlin, thanks",
  "looking for a backend engineer with 4 yrs experience near Boston",
  "get a product designer with 3+ years experience from Tokyo",
  "can you find a network engineer 7 years experienced in Zurich",
  "search for a solutions architect with 12 years of experience",
  "ok show me a data scientist 2 to 4 years located in Amsterdam",
  "please get me a research scientist with 9 years experience at Boston",
  "find me an operations manager with 15 years in Cairo",
  "show an analytics engineer in Dallas with at least 3 years",
  "give me a database administrator with 10 years experience in Madrid",
  "would you get a DevOps engineer in Singapore with 2–4 years for me",
  "hey, find a product manager in Paris with 5 to 7 years",
  "search for a UI designer in San Francisco with 2 years",
  "get me a cloud architect, 6+ years, in London",
  "please show a computer vision researcher with 5 years of experience",
  "looking for a marketing specialist with 3 years in Milan, thank you",
];
